### ISSUE TITLE
General: Add package.json to each plugin

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#3072]
### Tasks
1. Copy bower.json to package.json

### Plugins
- [x] [adapt-contrib-accordion](https://github.com/adaptlearning/adapt-contrib-accordion)
- [x] [adapt-contrib-assessment](https://github.com/adaptlearning/adapt-contrib-assessment)
- [x] [adapt-contrib-assessmentResults](https://github.com/adaptlearning/adapt-contrib-assessmentResults)
- [x] [adapt-contrib-blank](https://github.com/adaptlearning/adapt-contrib-blank)
- [x] [adapt-contrib-bookmarking](https://github.com/adaptlearning/adapt-contrib-bookmarking)
- [x] [adapt-contrib-boxMenu](https://github.com/adaptlearning/adapt-contrib-boxMenu)
- [ ] [adapt-contrib-core](https://github.com/adaptlearning/adapt-contrib-core)
- [x] [adapt-contrib-gmcq](https://github.com/adaptlearning/adapt-contrib-gmcq)
- [x] [adapt-contrib-graphic](https://github.com/adaptlearning/adapt-contrib-graphic)
- [x] [adapt-contrib-hotgraphic](https://github.com/adaptlearning/adapt-contrib-hotgraphic)
- [x] [adapt-contrib-languagePicker](https://github.com/adaptlearning/adapt-contrib-languagePicker)
- [x] [adapt-contrib-matching](https://github.com/adaptlearning/adapt-contrib-matching)
- [x] [adapt-contrib-mcq](https://github.com/adaptlearning/adapt-contrib-mcq)
- [x] [adapt-contrib-media](https://github.com/adaptlearning/adapt-contrib-media)
- [x] [adapt-contrib-narrative](https://github.com/adaptlearning/adapt-contrib-narrative)
- [x] [adapt-contrib-pageLevelProgress](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress)
- [x] [adapt-contrib-resources](https://github.com/adaptlearning/adapt-contrib-resources)
- [x] [adapt-contrib-slider](https://github.com/adaptlearning/adapt-contrib-slider)
- [x] [adapt-contrib-spoor](https://github.com/adaptlearning/adapt-contrib-spoor)
- [x] [adapt-contrib-text](https://github.com/adaptlearning/adapt-contrib-text)
- [x] [adapt-contrib-textInput](https://github.com/adaptlearning/adapt-contrib-textInput)
- [x] [adapt-contrib-trickle](https://github.com/adaptlearning/adapt-contrib-trickle)
- [x] [adapt-contrib-tutor](https://github.com/adaptlearning/adapt-contrib-tutor)
- [x] [adapt-contrib-vanilla](https://github.com/adaptlearning/adapt-contrib-vanilla)

**Comment by OlaoluwaM** [comment]
Hey @oliverfoster is this issue still available

**Comment by oliverfoster** [comment]
Yes it is. 👍

**Comment by OlaoluwaM** [comment]
Hey @oliverfoster , would it work to simply rename each bower.json file to a package.json?

**Comment by oliverfoster** [comment]
Nono, we need both files at the same time for the moment.

**Comment by OlaoluwaM** [comment]
Hey @oliverfoster I think the link for adapt-contrib-core is broken. It directed me to a 404 page

**Comment by oliverfoster** [comment]
It hasn't been created yet. I'll talk it through with the team on their Monday meeting. I effectively need to move src/core into it's own adapt-contrib-core and link it back into the current src/core folder.

**Comment by OlaoluwaM** [comment]
Hey @oliverfoster , I am done. Let me know when ``adapt-contrib-core`` is up so I can complete that. Thanks

**Comment by oliverfoster** [comment]
superb, thankyou!

**Comment by OlaoluwaM** [comment]
No problem

**Comment by oliverfoster** [comment]
@OlaoluwaM 

[adapt-contrib-core](https://github.com/adaptlearning/adapt-contrib-core) is ready, I have added a package.json in the work already. Thank you for doing the others, it was a great help.
